name: unity_ads_flutter
description: Unity Ads for Flutter
version: 1.1.0
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
homepage: https://github.com/epnw/unity_ads_flutter

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: eu.epnw.unityadsflutter
    pluginClass: UnityAdsFlutterPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"